app.base-url=${APP_BASE_URL:http://localhost:8080}

# ==== Actuator ====
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=never

spring.messages.basename=messages
spring.messages.encoding=UTF-8

# ==== Thymeleaf ====
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML
spring.thymeleaf.servlet.content-type=text/html

# ==== Email via Resend (HTTP API) ====
mail.resend.api-key=${RESEND_API_KEY:}
mail.resend.from=${MAIL_FROM:Book App <onboarding@resend.dev>}
app.mail.admin=${APP_MAIL_ADMIN:vlpiatachenko@gmail.com}

# ==== Logging ====
logging.level.sumdu.edu.ua.persistence=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ==== DATABASE: PostgreSQL (RENDER) ====
spring.datasource.url=jdbc:postgresql://dpg-d6tita3uibrs73ao8bpg-a:5432/mpf_labs_55px
spring.datasource.username=mpf_labs_55px_user
spring.datasource.password=JzpB2q2uOVHP953cAqM8UXrQXIkPdpGb
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==== Flyway ====
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ==== PORT (ВАЖЛИВО ДЛЯ RENDER) ====
server.port=${PORT:8080}
